### ISSUE TITLE
DosBox не собирается по приложенной инструкции

### ISSUE THREAD

**Issue by shershenuk-ra** [deadman2000/usb_opl2#1]
![Сборка_по_инструкции_с_Github](https://user-images.githubusercontent.com/76479138/102887445-09678980-4468-11eb-8e0f-400f52c45ccf.png)

**Comment by deadman2000** [comment]
Без патчей Dosbox собирается? Я не пробовал собирать через make, собирал в Visual Studio.

**Comment by shershenuk-ra** [comment]
Без патчей собирается нормально. Такое ощущение, что еще не хватает модифицированного adlib.h

**Comment by shershenuk-ra** [comment]
```
struct Chip {
	//Last selected register
	Timer timer0, timer1;
	//Check for it being a write to the timer
	bool Write( Bit32u addr, Bit8u val );
	//Read the current timer state, will use current double
	Bit8u Read( );

	Chip();
};
```
timer0, timer1 объявлены не как массив

**Comment by deadman2000** [comment]
предроложу что у вас другая версия DosBox. выложу нужные куски отдельно

**Comment by shershenuk-ra** [comment]
Проект для меня интересный и хотелось бы получить доступ к этим "кускам". Все таки иметь исходники как-то надежней, чем готовый exe-шник. Или хотя бы указать номер версии DosBox, для которой инструкция по сборке работает.

**Comment by deadman2000** [comment]
Файлы `hidlibrary.h`, `opl2usb.cpp` и `opl2usb.h` скопировать как есть в `src/hardware`.

В файле `adlib.cpp`
После include'ов:
```
#include "opl2usb.h"
```

Там где идет проверка параметра `oplemu` перед последним `else`:
```
	else if (oplemu == "usb") {
		handler = new OPL2USB::Handler();
	}
```

В файле `src/dosbox.cpp` в список валидных параметров `oplemus` добавить `"usb"`:
```
	const char* oplemus[]={ "default", "compat", "fast", "mame", "usb", 0};
```

**Comment by deadman2000** [comment]
Я использовал svn версию отсюда: svn://svn.code.sf.net/p/dosbox/code-0/dosbox/trunk
Ревизия 4180, но думаю будет работать и на последних

**Comment by shershenuk-ra** [comment]
Можно уточнить, в какой версии VS происходила сборка. Все попытки собрать под MinGW закончились неудачно

**Comment by deadman2000** [comment]
Сборка DosBox не относится к проблеме данного проекта
